---
# file: playbook.yaml

- hosts: localhost
  gather_facts: false 
  vars_files:
    - tf_ansible_vars_file.yaml
  tasks:
    - name: Check mandatory variables imported from Terraform
      assert:
        that:
          - tf_ceph_monitor_ip is defined
        fail_msg: "tf_* variable usually defined in './ansible/tf_ansible_vars_file.yaml' is missing"

- import_playbook: setup_nodes.yaml
  tags: setup_nodes

- import_playbook: setup_rook.yaml
  tags: setup_rook
