---
# file: setup_nodes.yaml

- hosts: ceph_nodes
  become: true
  tasks:
    - name: Ensure Podman is installed
      apt:
        name: 
        - podman
        state: present
        update_cache: yes
        

- hosts: ceph_node_1
  become: true
  vars_files:
    - tf_ansible_vars_file.yaml
  tasks:
    - name: Export values.yaml
      shell:
        cmd: |
          cephadm install ceph-common
    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: /tmp/ssh_keys
        state: directory
        mode: '0755' # Set appropriate permissions
    - name: Copy keys
      ansible.builtin.copy:
        src: ../.ssh/my-private-key.pem
        dest: /tmp/ssh_keys/ceph.pem
        mode: '0600'  # Owner read/write, no access for others
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
    - name: Copy keys
      ansible.builtin.copy:
        src: ../.ssh/my-public-key.pub
        dest: /tmp/ssh_keys/ceph.pub
        mode: '0600'  # Owner read/write, no access for others
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
    - name: Install cephadm 
      apt:
        name: 
         - cephadm
        state: present
        update_cache: yes # Optional: Updates package cache before installing
    - name: bootstrap cephadm
      shell:
        cmd: |
          cephadm bootstrap --mon-ip {{ private_ip }} --ssh-user {{ ansible_user }} --ssh-private-key /tmp/ssh_keys/ceph.pem --ssh-public-key /tmp/ssh_keys/ceph.pub
  tags: cephadm