- hosts: ceph_node_1
  become: true
  vars_files:
    - tf_ansible_vars_file.yaml
  tasks:
    - name: Clone the rook repository
      ansible.builtin.git:
        repo: 'https://github.com/rook/rook.git'
        dest: '/tmp/ceph-k8s/rook'
        clone: yes
        update: yes

    - name: Generate ceph-cluster.sh
      shell:
        cmd: |
          python3 create-external-cluster-resources.py --rbd-data-pool-name rbd --cephfs-filesystem-name cephfs --rgw-endpoint 192.168.254.109:8001  --namespace rook-ceph --format bash | tee /tmp/ceph-k8s/ceph-cluster.sh
          echo "source ./import-external-cluster.sh" >> /tmp/ceph-k8s/ceph-cluster.sh
        chdir: /tmp/ceph-k8s/rook/deploy/examples/external/

    - name: Copy env file to local machine
      ansible.builtin.fetch:
        src: /tmp/ceph-k8s/ceph-cluster.sh
        dest: "{{ playbook_dir }}/../_out/"
        flat: true

    - name: Copy crd file to local machine
      ansible.builtin.fetch:
        src: /tmp/ceph-k8s/rook/deploy/examples/crds.yaml
        dest: "{{ playbook_dir }}/../_out/"
        flat: true

    - name: Copy common file to local machine
      ansible.builtin.fetch:
        src: /tmp/ceph-k8s/rook/deploy/examples/common.yaml
        dest: "{{ playbook_dir }}/../_out/"
        flat: true

    - name: Copy csi-operator file to local machine
      ansible.builtin.fetch:
        src: /tmp/ceph-k8s/rook/deploy/examples/csi-operator.yaml
        dest: "{{ playbook_dir }}/../_out/"
        flat: true

    - name: Copy operator file to local machine
      ansible.builtin.fetch:
        src: /tmp/ceph-k8s/rook/deploy/examples/operator.yaml
        dest: "{{ playbook_dir }}/../_out/"
        flat: true

    - name: Copy common-external file to local machine
      ansible.builtin.fetch:
        src: /tmp/ceph-k8s/rook/deploy/examples/common-external.yaml
        dest: "{{ playbook_dir }}/../_out/"
        flat: true

    - name: Copy cluster-external file to local machine
      ansible.builtin.fetch:
        src: /tmp/ceph-k8s/rook/deploy/examples/cluster-external.yaml
        dest: "{{ playbook_dir }}/../_out/"
        flat: true

    - name: Copy import-external-cluster file to local machine
      ansible.builtin.fetch:
        src: /tmp/ceph-k8s/rook/deploy/examples/import-external-cluster.sh
        dest: "{{ playbook_dir }}/../_out/"
        flat: true

    

- name: Manage Kubernetes objects on localhost
  hosts: localhost
  connection: local
  vars:
    current_working_dir: "{{ lookup('env', 'PWD') }}"
  tasks:
    - name: Apply _out/crds.yaml
      ansible.builtin.shell:
        cmd: |
          kubectl apply -f crds.yaml
        chdir: "{{ current_working_dir }}/_out/"
    - name: Apply _out/common.yaml
      ansible.builtin.shell:
        cmd: |
          kubectl apply -f common.yaml
        chdir: "{{ current_working_dir }}/_out/"
    - name: Apply _out/csi-operator.yaml
      ansible.builtin.shell:
        cmd: |
          kubectl apply -f csi-operator.yaml
        chdir: "{{ current_working_dir }}/_out/"
    - name: Apply _out/operator.yaml
      ansible.builtin.shell:
        cmd: |
          kubectl apply -f operator.yaml
        chdir: "{{ current_working_dir }}/_out/"

    - name: Apply _out/common-external.yaml
      ansible.builtin.shell:
        cmd: |
          kubectl apply -f common-external.yaml
        chdir: "{{ current_working_dir }}/_out/"

    - name: Apply _out/cluster-external.yaml
      ansible.builtin.shell:
        cmd: |
          kubectl apply -f cluster-external.yaml
        chdir: "{{ current_working_dir }}/_out/"

    - name: Import external cluster
      ansible.builtin.shell:
        cmd: |
          bash ceph-cluster.sh
        chdir: "{{ current_working_dir }}/_out/"